function s = sigmas
  s = struct( ...
    'g',           0,         ...
    'c_disch',     0,         ...
    'rho_atmo',    0.1,       ...
    'vol_bottle',  0.0005,    ...
    'P_amb',       0.005,     ...
    'g_air',       0,         ...
    'rho_w',       0.1,       ...
    'D_t',         0,         ...
    'bottle_diam', 0,         ...
    'R',           0,         ...
    'm_empty',     2/1000,    ...
    'T0',          5,         ...
    'Cd',          0.05,      ...
    'P0',          0,         ...
    'Vol_water_0', 5/1000,    ...
    'v0',          0,         ...
    'hdg0',        0,         ...
    'tmax',        0         ...
  );
end
